// Dynamic Groovy mapping to redirect jcenter() to mavenCentral() for all subprojects
org.gradle.api.artifacts.dsl.RepositoryHandler.metaClass.jcenter = { ->
    delegate.mavenCentral()
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
