name: sajna_ai
description: SAJNA AI - Offline-First Cabin Crew Assistant for Air Arabia.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  sqlite3: ^2.3.0
  sqflite: ^2.3.0
  intl: ^0.18.1
  speech_to_text: ^6.1.1
  pdf: ^3.10.4
  docx_template: ^0.2.1
  share_plus: ^7.1.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.2.3
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
#  assets:
#    - assets/manuals/
#    - assets/data/
