name: sajna_ai
description: SAJNA AI - Offline-First Cabin Crew Assistant for Air Arabia.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
